noun1 = input('pick a noun')
pnoun1 = input('pick a plural noun')
noun2 = input('pick another noun')
place = input('pick a place')
adjective = input('pick an adjective')
print('Did you know I have a pet ' + noun1 + '?')
print('He likes to run around and play with all of the ' + pnoun1 + '.')
print('One morning, I work up and he was wearing a ' + noun2 + ' for a hat!')
print('I espescially like to take him to the ' + place + ' because he shows off his ' + adjective + ' side.')